services:
  app:
    image: morchv/dev-box:local-${DEVCONTAINER_USERNAME:-dev}
    environment:
      - HOME=/home/${DEVCONTAINER_USERNAME:-dev}
      - TERM
      - LOCAL_LLM_API_KEY
      - FIRECRAWL_API_KEY
      - FIRECRAWL_API_URL
    command: sleep infinity
    working_dir: /workspace/${COMPOSE_PROJECT_NAME}
    volumes:
      - ..:/workspace/${COMPOSE_PROJECT_NAME}
      - ${DEVCONTAINER_HOME:-${HOME}/.devcontainers-home}:/home/${DEVCONTAINER_USERNAME:-dev}
      - /home/${DEVCONTAINER_USERNAME:-dev}/.vscode-server
    ports:
      - "8000:8000"
