services:
  devcontainer:
    image: ${PI_BOX_IMAGE:-morchv/pi-box:latest}
    container_name: pi-box_${COMPOSE_PROJECT_NAME}
    hostname: devcontainer
    env_file:
      - path: ${PI_BOX_ENV_FILE:-${PI_BOX_ROOT:-~/.pi-box}/pi-box.env}
        required: false
    working_dir: /workspace/${COMPOSE_PROJECT_NAME}
    volumes:
      - "..:/workspace/${COMPOSE_PROJECT_NAME}:z"
      - "${PI_BOX_ROOT:-~/.pi-box}/home:/home/pi:z"
      - "/home/pi/.vscode-server"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
