ARG NODE_VERSION=26.7.0
ARG PYTHON_VERSION=3.14.7
ARG UV_VERSION=0.12.3
ARG PI_VERSION=0.84.1

FROM ghcr.io/astral-sh/uv:${UV_VERSION} AS uv
FROM node:${NODE_VERSION}-slim AS node
FROM python:${PYTHON_VERSION}-slim

COPY --from=node /usr/local/ /usr/local/
COPY --from=uv /uv /uvx /bin/

ARG PI_VERSION
RUN set -eux \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    libnss-wrapper \
    bash \
    curl \
    ca-certificates \
    fd-find \
    git \
    openssh-client \
    ripgrep \
    jq \
    build-essential \
    vim \
    podman \
    podman-compose \
    fuse-overlayfs \
    iptables \
    wget \
    pipx \
    musl-dev \
  && rm -rf /var/lib/apt/lists/* \
  && npm install --global --omit=dev "@earendil-works/pi-coding-agent@${PI_VERSION}" \
  && npm cache clean --force

ARG USERNAME=pi
ARG UID=1000
ARG GID=1000

ENV TERM=xterm-256color
ENV HOME=/home/${USERNAME}

RUN set -eux \
  && groupadd -g "${GID}" "${USERNAME}" \
  && useradd -u "${UID}" -g "${USERNAME}" -m -s /bin/bash "${USERNAME}" \
  && mkdir -p "${HOME}/.vscode-server" \
  && chown -R "${USERNAME}:${USERNAME}" "${HOME}" \
  && echo "${USERNAME}:10000:65536" > /etc/subuid \
  && echo "${USERNAME}:10000:65536" > /etc/subgid \
  && ln -s /usr/bin/podman /usr/bin/docker

LABEL capabilities.required="SETUID,SETGID,SYS_CHROOT,SETFCAP"
LABEL capabilities.description="SETUID, SETGID, SYS_CHROOT, SETFCAP required for podman support"

USER "${USERNAME}"

CMD ["pi"]
